sudo: required
dist: trusty
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -y
  - sudo apt-get install qemu-kvm -y
  - sudo apt-get install libxen-dev -y
  - sudo apt-get install g++-4.8 bc -y
  - git clone https://github.com/rumpkernel/rumprun
language: go
script:
  - export CC=gcc-4.8
  - export CXX=g++-4.8
  - cd rumprun && git submodule update --init
  - CC=cc ./build-rr.sh hw 1> /dev/null
  - mkdir $HOME/gopath/src/github.com/deferpanic/gorump/rumprun/build &&  tar -zcvf rumprun.tar.gz rumprun/ && mv rumprun.tar.gz $HOME/gopath/src/github.com/deferpanic/gorump/rumprun/build/.
  - cd $HOME/gopath/src/github.com/deferpanic/gorump/go/src && CGO_ENABLED=1 GOROOT_BOOTSTRAP=$GOROOT GOOS=netbsd GOARCH=amd64 ./make.bash
  - cd $HOME/gopath/src/github.com/deferpanic/gorump/test/gc_test && GOROOT=$HOME/gopath/src/github.com/deferpanic/gorump/go PATH=$PATH:$HOME/gopath/src/github.com/deferpanic/gorump/rumprun/rumprun/bin make && ./verify_gc.sh
  # - mkdir $HOME/gopath/src/github.com/deferpanic/gorump/build && cd $HOME/gopath/src/github.com/deferpanic/gorump && tar -zcvf gorump.tar.gz go/ && mv gorump.tar.gz build/.

notifications:
  email:
    recipients:
      - engineering@deferpanic.com
#deploy:
#    - provider: s3
#      access_key_id: $ARTIFACTS_KEY
#      secret_access_key: $ARTIFACTS_SECRET
#      bucket: $ARTIFACTS_BUCKET
#      region: us-east-1
#      skip_cleanup: true
#      local-dir: $HOME/gopath/src/github.com/deferpanic/gorump/build
#      acl: public_read
#      detect_encoding: true  
#    - provider: s3
#      access_key_id: $ARTIFACTS_KEY
#      secret_access_key: $ARTIFACTS_SECRET
#      bucket: $ARTIFACTS_BUCKET
#      region: us-east-1
#      skip_cleanup: true
#      local-dir: $HOME/gopath/src/github.com/deferpanic/gorump/rumprun/build
#      acl: public_read
#      detect_encoding: true
